getfindmutex.go
getfindmutex_test.go
source.go

GFMs are now specific to type + context

---

engine.go
go.mod
requests.go
requests_test.go
source.go
source_test.go

Ignore cache

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.devcontainer/nats/nats-server.conf
.gitignore
.vscode/extensions.json
.vscode/tasks.json
README.md
engine.go
engine_test.go
go.mod
request_tracker.go
request_tracker_test.go
requests.go
requests_test.go
shared_test.go
source.go
source_test.go

This PR allows requests to be cancelled. Note that it includes a change to the `Source` interface and will therefore be a breaking change for all downstream projects. Fixes #16

Cancellation

---

request_tracker.go
request_tracker_test.go

This will hopefully fix #23 but I haven't been able to replicate

Added more protection for nil pointers

---

go.mod
item_tests.go
requests_test.go

Creates a naming convention for item types: RFC1123

Type naming

---

engine.go
engine_test.go
go.mod
requests_test.go

Added handling for NATS reconnects

---

.github/workflows/test.yml
engine.go
engine_test.go
go.mod
nats_watcher.go
nats_watcher_test.go

Added engine restart on completely lost connection

---

.devcontainer/docker-compose.yml
.github/workflows/test.yml
go.mod
go.sum
nats_shared_test.go

Dependencies have been automatically updated
**Note:** Automatic tests will not run on this dut to it being created by an action. However the following has already passed:
```
go test ./... -race
```

[AUTO] Updated Dependencies

---

engine.go
requests.go
requests_test.go

NATS Subscriptions don't call handlers in goroutines by default, so we need to change this to spawn goroutines for handlers

Async subscriptions

---

.devcontainer/Dockerfile
.github/workflows/test.yml
engine.go
engine_test.go
requests.go

Requests can no longer have an infinite timeout and deadlock the engine

Added max request timeout

---

request_tracker.go

Removed a bunch of redundant code left over from a refactor

Execute redundancy

---

source_test.go

This ensures that an item found using SEARCH will be cached for future GET requests too

Added teste for Search -> Get caching

---

engine.go
enginerequests.go

Since LIST requests can block GET requests to load up the cache better, there is a slight chance of a deadlock if too many get requests make it into the pool before the LIST request. This creates a separate pool for LIST requests to ensure that they can't deadlock waiting on the shared pool.

Use separate executions pools for LIST requests and everything else

---

.github/workflows/test.yml

See https://github.com/hoverkraft-tech/compose-action/issues/42

Follow isbang/compose-action move to hoverkraft-tech/compose-action

---

engine.go
heartbeat.go
heartbeat_test.go

Also fixed a lint issue "Non-inherited new context" with the contexts

Make sure we always sends one heartbeat immediately

---

cmd.go
cmd_test.go
engine.go
heartbeat.go
heartbeat_test.go

RE https://github.com/overmindtech/discovery/issues/361
NATS only 
using an api key
NB debug of  printing the keys is removed.

(feat) add source-access-token functionality

---

cmd.go

This is related to https://github.com/overmindtech/api-server/issues/1235
We need to be able to start sources with no auth at all for tests, this is what is causing the tests in api-server CI to fail

Allow unauthenticated NATS

---

README.md
cmd.go
cmd_test.go
engine.go
engine_test.go
go.mod
heartbeat.go
heartbeat_test.go

re https://github.com/overmindtech/discovery/issues/376

(maint) centralise nats configuration

---

cmd.go
cmd_test.go

This will be determined wither using the --app option, or via the K8s-provided env vars now

Remove the nats-servers option

---

README.md
cmd.go
cmd_test.go
engine.go

Remove nats auth 🍫 [minting]

---

enginerequests.go
enginerequests_test.go

Also make sure that they all get captured in spans

Standardise the way we handle errors

---

enginerequests.go

Only create on if we actually have an adapter that matches the query and therefore we are going to try to respond

Reduce the number of spans
